export const FETCH_DEFINITION_REQUEST = 'FETCH_DEFINITION_REQUEST';
export const FETCH_DEFINITION_SUCCESS = 'FETCH_DEFINITION_SUCCESS';
export const FETCH_DEFINITION_FAILURE = 'FETCH_DEFINITION_FAILURE';